name: CICD

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      run: |
        # Run commands to build and push Docker images
        docker build -t nodeapp .
        docker tag nodeapp shubhz1452/nodejs-app:latest
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push shubhz1452/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Docker pull image
      run: docker-compose pull
    - name: Deploy to container
      run: docker-compose up -d
