name: CICD

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'Readme.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{github.run_id}}
    - name: Deploy to Server
      run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ubuntu@${{ secrets.SERVER_HOST }} "cd ${{ secrets.WORK_DIR }} && docker-compose down && docker-compose pull && docker-compose up -d && exit"
    - name: cleanup
      run: rm -rf ~/.ssh 
